"""Generate data/encodings/ — the 6 native-geometry files (6 geometry types).

Each file holds 3-5 rows: one or more concrete geometries, one EMPTY, one NULL.
Native-geometry uses OGC:CRS84 planar.

The 6 native-geography variants (Parquet native Geography logical type) are
produced separately by gen_geography.py using Apache sedonadb (the only tool in
our stack that emits that logical type). This script does NOT generate them, but
its README lists all 12 files.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import geoarrow.pyarrow as ga
import pyarrow as pa

# Make sibling package importable when running as a script
sys.path.insert(0, str(Path(__file__).resolve().parent))

from gpqgen.crs import CRS84
from gpqgen.metadata import make_geo_metadata
from gpqgen.paths import DATA_DIR, ensure_dir
from gpqgen.write import write_parquet_deterministic

OUT_DIR = DATA_DIR / "encodings"


# Geometry-type -> list of WKT strings (last entry is None, second-last is EMPTY).
SAMPLES: dict[str, list[str | None]] = {
    "point": [
        "POINT (30 10)",
        "POINT (40 40)",
        "POINT EMPTY",
        None,
    ],
    "linestring": [
        "LINESTRING (30 10, 10 30, 40 40)",
        "LINESTRING EMPTY",
        None,
    ],
    "polygon": [
        "POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))",
        "POLYGON ((35 10, 45 45, 15 40, 10 20, 35 10), (20 30, 35 35, 30 20, 20 30))",
        "POLYGON EMPTY",
        None,
    ],
    "multipoint": [
        "MULTIPOINT ((30 10))",
        "MULTIPOINT ((10 40), (40 30), (20 20), (30 10))",
        "MULTIPOINT EMPTY",
        None,
    ],
    "multilinestring": [
        "MULTILINESTRING ((30 10, 10 30, 40 40))",
        "MULTILINESTRING ((10 10, 20 20, 10 40), (40 40, 30 30, 40 20, 30 10))",
        "MULTILINESTRING EMPTY",
        None,
    ],
    "multipolygon": [
        "MULTIPOLYGON (((30 10, 40 40, 20 40, 10 20, 30 10)))",
        "MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20)), ((15 5, 40 10, 10 20, 5 10, 15 5)))",
        "MULTIPOLYGON EMPTY",
        None,
    ],
}

# Display-cased geometry types for `geometry_types` metadata.
GEOMETRY_TYPE_CASE = {
    "point": "Point",
    "linestring": "LineString",
    "polygon": "Polygon",
    "multipoint": "MultiPoint",
    "multilinestring": "MultiLineString",
    "multipolygon": "MultiPolygon",
}


def _write_one(geom_key: str, encoding: str) -> Path:
    """Write one native-geometry encoding-tier file."""
    wkt_list = SAMPLES[geom_key]
    table = pa.table(
        {
            "col": list(range(len(wkt_list))),
            "geometry": ga.as_wkb(wkt_list),
        }
    )
    column_meta: dict[str, Any] = {
        "encoding": "WKB",
        "geometry_types": [GEOMETRY_TYPE_CASE[geom_key]],
        "crs": CRS84,
        "edges": "planar",
    }

    geo_meta = make_geo_metadata(columns={"geometry": column_meta})
    out_path = OUT_DIR / f"{geom_key}-{encoding}.parquet"
    write_parquet_deterministic(table, out_path, geo_meta)
    return out_path


def _write_readme() -> None:
    lines = [
        "# data/encodings/",
        "",
        "GeoParquet 2.0 has a single encoding (`\"WKB\"`); the variation here is whether the "
        "Parquet column uses the native Geometry or native Geography logical type. "
        "The native-geometry (planar `OGC:CRS84`) files are generated by this script "
        "(`gen_encodings.py`, via pyarrow). The native-geography files (Parquet native "
        "Geography logical type, spherical edges) are generated by `gen_geography.py` using "
        "Apache sedonadb — the only tool in our stack that emits that logical type — and are "
        "committed as snapshots (see `scripts/README.md`, \"Geography tier\").",
        "",
        "| File | Geometry type | Encoding | CRS | Edges |",
        "|---|---|---|---|---|",
    ]
    for geom_key, cased in GEOMETRY_TYPE_CASE.items():
        for encoding in ("native-geometry", "native-geography"):
            edges = "spherical" if encoding == "native-geography" else "planar"
            lines.append(f"| `{geom_key}-{encoding}.parquet` | {cased} | {encoding} | OGC:CRS84 | {edges} |")
    (OUT_DIR / "README.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    ensure_dir(OUT_DIR)
    for geom_key in SAMPLES:
        for encoding in ("native-geometry",):
            out = _write_one(geom_key, encoding)
            print(f"  wrote {out.relative_to(OUT_DIR.parent.parent)}")
    _write_readme()


if __name__ == "__main__":
    main()
